#!/usr/bin/env python3
"""
Runs demo
"""
from __future__ import absolute_import, division, print_function

import sys
import os
import argparse

from ioflo.aid.sixing import *

from ioflo.base import consoling
console = consoling.getConsole()

from mauga.demoing import solution

def parseArgs():
    """
    Parse command line arguments

    """

    d = "Runs example. "
    d += "Example: run -f filename \n"
    p = argparse.ArgumentParser(description=d)
    p.add_argument('-v', '--verbose',
            action='store',
            default='concise',
            choices=['0', '1', '2', '3', '4'].extend(consoling.VERBIAGE_NAMES),
            help="Verbosity level.")
    p.add_argument('-c', '--console',
        action='store',
        default='',
        help="File path name to console log file.")
    p.add_argument('-f', '--filepath',
            action='store',
            required=False,
            help="File path.")
    args = p.parse_args()

    if args.verbose in consoling.VERBIAGE_NAMES:
        verbosage = consoling.VERBIAGE_NAMES.index(args.verbose)
    else:
        verbosage = int(args.verbose)

    console = consoling.getConsole(verbosity=consoling.Console.Wordage[verbosage],
                                   path=args.console)
    console.profuse('run arguments: \n{0}'.format(args))
    args.verbose = verbosage  # converted value
    return args


if __name__ == "__main__":
    #args = parseArgs()

    x = [1, 0, 0, 1, 1]
    y = solution(x)
    print(x, y)

    x = [1, 1, 0, 1, 0, 1, 1]
    y = solution(x)
    print(x, y)

    x = [1, 1, 0, 0, 1]
    y = solution(x)
    print(x, y)
